version: '2'
services:
  web:
    image: ipioneers/passenger-ruby:2.3
    expose:
      - 80
    volumes:
      - .:/home/app
      - ../../shared:${CAP_DOCKER_COMPOSE_ROOT_PATH}/shared
    ports:
      - "${CAP_DOCKER_COMPOSE_PORT}:80"
    environment:
      - RAILS_ENV=staging
      - PASSENGER_APP_ENV=staging
  db:
    image: postgres:9.5
    environment:
      - POSTGRES_DB=staging
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=staging_user
      - POSTGRES_PASSWORD=soZee4Ig+u1f
    volumes:
      - ../../shared/postgresql:/var/lib/postgresql/data/pgdata
